bank_vault: bank_vault.c libhfsecurity.a
	gcc bank_vault.c -I. -L. -lhfsecurity -o bank_vault
encrypt.o: encrypt.h encrypt.c
	gcc -c encrypt.c -o encrypt.o
checksum.o: checksum.h checksum.c
	gcc -c checksum.c -o checksum.o
libhfsecurity.a: encrypt.o checksum.o
	ar -rcs libhfsecurity.a encrypt.o checksum.o